apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: my-app
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nicat471/my_app:VERSION
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: myapp-secret
